
// This file has been generated by the GUI designer. Do not modify.
namespace IDNetSoftware
{
	public partial class ConnectionDialog
	{
		private global::Gtk.VBox vbox3;

		private global::Gtk.Button buttonConexion;

		private global::Gtk.Button buttonEsquema;

		private global::Gtk.Button buttonSelect;

		private global::Gtk.Button buttonCancel;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget IDNetSoftware.ConnectionDialog
			this.Name = "IDNetSoftware.ConnectionDialog";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child IDNetSoftware.ConnectionDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.buttonConexion = new global::Gtk.Button();
			this.buttonConexion.CanFocus = true;
			this.buttonConexion.Name = "buttonConexion";
			this.buttonConexion.UseUnderline = true;
			this.buttonConexion.Label = global::Mono.Unix.Catalog.GetString("Establecer conexión");
			this.vbox3.Add(this.buttonConexion);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.buttonConexion]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.buttonEsquema = new global::Gtk.Button();
			this.buttonEsquema.CanFocus = true;
			this.buttonEsquema.Name = "buttonEsquema";
			this.buttonEsquema.UseUnderline = true;
			this.buttonEsquema.Label = global::Mono.Unix.Catalog.GetString("Solicitar Esquema de la BBDD");
			this.vbox3.Add(this.buttonEsquema);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.buttonEsquema]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.buttonSelect = new global::Gtk.Button();
			this.buttonSelect.CanFocus = true;
			this.buttonSelect.Name = "buttonSelect";
			this.buttonSelect.UseUnderline = true;
			this.buttonSelect.Label = global::Mono.Unix.Catalog.GetString("Realizar consulta");
			this.vbox3.Add(this.buttonSelect);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.buttonSelect]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			w1.Add(this.vbox3);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(w1[this.vbox3]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Internal child IDNetSoftware.ConnectionDialog.ActionArea
			global::Gtk.HButtonBox w6 = this.ActionArea;
			w6.Name = "dialog1_ActionArea";
			w6.Spacing = 10;
			w6.BorderWidth = ((uint)(5));
			w6.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget(this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w7 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w6[this.buttonCancel]));
			w7.Expand = false;
			w7.Fill = false;
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 168;
			this.Show();
			this.buttonConexion.Clicked += new global::System.EventHandler(this.OnButtonConexionClicked);
			this.buttonEsquema.Clicked += new global::System.EventHandler(this.OnButtonEsquemaClicked);
			this.buttonSelect.Clicked += new global::System.EventHandler(this.OnButtonSelectClicked);
			this.buttonCancel.Clicked += new global::System.EventHandler(this.OnButtonCancelClicked);
		}
	}
}
