
// This file has been generated by the GUI designer. Do not modify.
namespace IDNetSoftware
{
	public partial class SplashWindow
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.Image IDNetimage;

		private global::Gtk.Label labelInfoTFG;

		private global::Gtk.HBox hbox1;

		private global::Gtk.ProgressBar progressbar;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget IDNetSoftware.SplashWindow
			this.Name = "IDNetSoftware.SplashWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("Bienvenido al mundo IDNet!");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource("iconoIDNetSoftware");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.Resizable = false;
			// Container child IDNetSoftware.SplashWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.IDNetimage = new global::Gtk.Image();
			this.IDNetimage.Name = "IDNetimage";
			this.IDNetimage.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("iconoIDNetSoftware");
			this.vbox1.Add(this.IDNetimage);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.IDNetimage]));
			w1.Position = 0;
			w1.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.labelInfoTFG = new global::Gtk.Label();
			this.labelInfoTFG.Name = "labelInfoTFG";
			this.labelInfoTFG.LabelProp = global::Mono.Unix.Catalog.GetString("Trabajo de Fin de Grado en el Grado en Ingeniería Informática\nAlumnos: Juan Mas A" +
					"guilar y Lorenzo José de la Paz Suárez");
			this.labelInfoTFG.Justify = ((global::Gtk.Justification)(2));
			this.vbox1.Add(this.labelInfoTFG);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.labelInfoTFG]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.progressbar = new global::Gtk.ProgressBar();
			this.progressbar.Name = "progressbar";
			this.progressbar.Text = global::Mono.Unix.Catalog.GetString("Cargando...");
			this.hbox1.Add(this.progressbar);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.progressbar]));
			w3.Position = 0;
			this.vbox1.Add(this.hbox1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 512;
			this.DefaultHeight = 584;
			this.Show();
		}
	}
}
