
// This file has been generated by the GUI designer. Do not modify.
namespace IDNetSoftware
{
	public partial class MainWindow
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Action ArchivoAction;

		private global::Gtk.Action EdicinAction;

		private global::Gtk.Action BasesDeDatosAction;

		private global::Gtk.Action OVAction;

		private global::Gtk.Action AyudaAction;

		private global::Gtk.Action SalirAction;

		private global::Gtk.Action salirAction;

		private global::Gtk.Action addDatabasePngAction;

		private global::Gtk.Action addAction;

		private global::Gtk.VBox vbox1;

		private global::Gtk.MenuBar menubar2;

		private global::Gtk.Toolbar toolbar1;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TextView infoview;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Frame frame1;

		private global::Gtk.Alignment GtkAlignment;

		private global::Gtk.Label GtkLabel7;

		private global::Gtk.Alignment alignment4;

		private global::Gtk.Alignment alignment5;

		private global::Gtk.ScrolledWindow GtkScrolledWindow1;

		private global::Gtk.TreeView treeviewDatabases;

		private global::Gtk.Statusbar statusbar;

		private global::Gtk.Label conexionesLabel;

		private global::Gtk.Label brandLabel;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget IDNetSoftware.MainWindow
			this.UIManager = new global::Gtk.UIManager();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
			this.ArchivoAction = new global::Gtk.Action("ArchivoAction", global::Mono.Unix.Catalog.GetString("Archivo"), null, null);
			this.ArchivoAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Archivo");
			w1.Add(this.ArchivoAction, null);
			this.EdicinAction = new global::Gtk.Action("EdicinAction", global::Mono.Unix.Catalog.GetString("Edición"), null, null);
			this.EdicinAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Edición");
			w1.Add(this.EdicinAction, null);
			this.BasesDeDatosAction = new global::Gtk.Action("BasesDeDatosAction", global::Mono.Unix.Catalog.GetString("Bases de Datos"), null, null);
			this.BasesDeDatosAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Bases de Datos");
			w1.Add(this.BasesDeDatosAction, null);
			this.OVAction = new global::Gtk.Action("OVAction", global::Mono.Unix.Catalog.GetString("O.V"), null, null);
			this.OVAction.ShortLabel = global::Mono.Unix.Catalog.GetString("O.V");
			w1.Add(this.OVAction, null);
			this.AyudaAction = new global::Gtk.Action("AyudaAction", global::Mono.Unix.Catalog.GetString("Ayuda"), null, null);
			this.AyudaAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Ayuda");
			w1.Add(this.AyudaAction, null);
			this.SalirAction = new global::Gtk.Action("SalirAction", global::Mono.Unix.Catalog.GetString("Salir"), null, null);
			this.SalirAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Salir");
			w1.Add(this.SalirAction, null);
			this.salirAction = new global::Gtk.Action("salirAction", global::Mono.Unix.Catalog.GetString("Salir"), null, "gtk-close");
			this.salirAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Salir");
			w1.Add(this.salirAction, null);
			this.addDatabasePngAction = new global::Gtk.Action("addDatabasePngAction", null, null, "addDatabase.png");
			w1.Add(this.addDatabasePngAction, null);
			this.addAction = new global::Gtk.Action("addAction", global::Mono.Unix.Catalog.GetString("Añadir"), null, "gtk-add");
			this.addAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Añadir");
			w1.Add(this.addAction, null);
			this.UIManager.InsertActionGroup(w1, 0);
			this.AddAccelGroup(this.UIManager.AccelGroup);
			this.WidthRequest = 700;
			this.HeightRequest = 500;
			this.Name = "IDNetSoftware.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("IDNet");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Resizable = false;
			// Container child IDNetSoftware.MainWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString(@"<ui><menubar name='menubar2'><menu name='ArchivoAction' action='ArchivoAction'><menuitem name='salirAction' action='salirAction'/></menu><menu name='EdicinAction' action='EdicinAction'/><menu name='BasesDeDatosAction' action='BasesDeDatosAction'><menuitem name='addAction' action='addAction'/></menu><menu name='OVAction' action='OVAction'/><menu name='AyudaAction' action='AyudaAction'/></menubar></ui>");
			this.menubar2 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar2")));
			this.menubar2.Name = "menubar2";
			this.vbox1.Add(this.menubar2);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.menubar2]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString("<ui><toolbar name=\'toolbar1\'><toolitem name=\'addDatabasePngAction\' action=\'addDat" +
					"abasePngAction\'/></toolbar></ui>");
			this.toolbar1 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/toolbar1")));
			this.toolbar1.Name = "toolbar1";
			this.toolbar1.ShowArrow = false;
			this.vbox1.Add(this.toolbar1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.toolbar1]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.infoview = new global::Gtk.TextView();
			this.infoview.Buffer.Text = @"Command: 001 - Solicitud de conexión a 'Lorenzo' 
Response: 004 - Conexión establecida
Command: 002 - Solicitud a la información de la base de datos 'empleados'
Response: 005 - Información enviada
Command: 003 - Solicitud de consulta a la tabla 'empleados Planta 1'
Response: 006 - Consulta realizada
";
			this.infoview.Name = "infoview";
			this.infoview.Editable = false;
			this.infoview.CursorVisible = false;
			this.infoview.AcceptsTab = false;
			this.GtkScrolledWindow.Add(this.infoview);
			this.vbox1.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.GtkScrolledWindow]));
			w5.Position = 2;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			this.frame1.Add(this.GtkAlignment);
			this.GtkLabel7 = new global::Gtk.Label();
			this.GtkLabel7.Name = "GtkLabel7";
			this.GtkLabel7.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Mis BBDD</b>");
			this.GtkLabel7.UseMarkup = true;
			this.frame1.LabelWidget = this.GtkLabel7;
			this.hbox1.Add(this.frame1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.frame1]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.alignment4 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment4.Name = "alignment4";
			// Container child alignment4.Gtk.Container+ContainerChild
			this.alignment5 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment5.Name = "alignment5";
			// Container child alignment5.Gtk.Container+ContainerChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.treeviewDatabases = new global::Gtk.TreeView();
			this.treeviewDatabases.CanFocus = true;
			this.treeviewDatabases.Name = "treeviewDatabases";
			this.GtkScrolledWindow1.Add(this.treeviewDatabases);
			this.alignment5.Add(this.GtkScrolledWindow1);
			this.alignment4.Add(this.alignment5);
			this.hbox1.Add(this.alignment4);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.alignment4]));
			w11.Position = 1;
			this.vbox1.Add(this.hbox1);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
			w12.Position = 3;
			// Container child vbox1.Gtk.Box+BoxChild
			this.statusbar = new global::Gtk.Statusbar();
			this.statusbar.Name = "statusbar";
			this.statusbar.Homogeneous = true;
			this.statusbar.Spacing = 6;
			// Container child statusbar.Gtk.Box+BoxChild
			this.conexionesLabel = new global::Gtk.Label();
			this.conexionesLabel.Name = "conexionesLabel";
			this.conexionesLabel.LabelProp = global::Mono.Unix.Catalog.GetString("0 conexiones activas");
			this.statusbar.Add(this.conexionesLabel);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.statusbar[this.conexionesLabel]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			// Container child statusbar.Gtk.Box+BoxChild
			this.brandLabel = new global::Gtk.Label();
			this.brandLabel.Name = "brandLabel";
			this.brandLabel.LabelProp = global::Mono.Unix.Catalog.GetString("IDNet Software");
			this.statusbar.Add(this.brandLabel);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.statusbar[this.brandLabel]));
			w14.Position = 2;
			w14.Expand = false;
			w14.Fill = false;
			this.vbox1.Add(this.statusbar);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.statusbar]));
			w15.Position = 4;
			w15.Expand = false;
			w15.Fill = false;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 732;
			this.DefaultHeight = 500;
			this.Show();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
			this.salirAction.Activated += new global::System.EventHandler(this.OnSalirActionActivated);
			this.addDatabasePngAction.Activated += new global::System.EventHandler(this.OnAddDatabasePngActionActivated);
			this.addAction.Activated += new global::System.EventHandler(this.OnAddActionActivated);
		}
	}
}
