
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.Button mongoPlugin;

	private global::Gtk.Button mysqlPlugin;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TextView textContent;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.mongoPlugin = new global::Gtk.Button();
		this.mongoPlugin.CanFocus = true;
		this.mongoPlugin.Name = "mongoPlugin";
		this.mongoPlugin.UseUnderline = true;
		this.mongoPlugin.Label = global::Mono.Unix.Catalog.GetString("mongoPlugin");
		this.vbox1.Add(this.mongoPlugin);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.mongoPlugin]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.mysqlPlugin = new global::Gtk.Button();
		this.mysqlPlugin.CanFocus = true;
		this.mysqlPlugin.Name = "mysqlPlugin";
		this.mysqlPlugin.UseUnderline = true;
		this.mysqlPlugin.Label = global::Mono.Unix.Catalog.GetString("mysqlPlugin");
		this.vbox1.Add(this.mysqlPlugin);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.mysqlPlugin]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.textContent = new global::Gtk.TextView();
		this.textContent.CanFocus = true;
		this.textContent.Name = "textContent";
		this.textContent.Editable = false;
		this.GtkScrolledWindow.Add(this.textContent);
		this.vbox1.Add(this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.GtkScrolledWindow]));
		w4.Position = 2;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.mongoPlugin.Clicked += new global::System.EventHandler(this.OnMongoPluginClicked);
		this.mysqlPlugin.Clicked += new global::System.EventHandler(this.OnMysqlPluginClicked);
	}
}
