
// This file has been generated by the GUI designer. Do not modify.
namespace IDNetSoftware
{
	public partial class LoginWindow
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.VBox vbox3;

		private global::Gtk.Label labelIniciarSesion;

		private global::Gtk.Image imageIDNet;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Label labelUsuario;

		private global::Gtk.Entry entryUser;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Label labelContrasenia;

		private global::Gtk.Entry entryPassword;

		private global::Gtk.HBox hbox3;

		private global::Gtk.Button buttonRegister;

		private global::Gtk.Label labelState;

		private global::Gtk.Button buttonOk;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget IDNetSoftware.LoginWindow
			this.Name = "IDNetSoftware.LoginWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("IDNet");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource("iconoIDNetSoftware");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Container child IDNetSoftware.LoginWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.labelIniciarSesion = new global::Gtk.Label();
			this.labelIniciarSesion.Name = "labelIniciarSesion";
			this.labelIniciarSesion.LabelProp = global::Mono.Unix.Catalog.GetString("Iniciar sesión");
			this.vbox3.Add(this.labelIniciarSesion);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.labelIniciarSesion]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.imageIDNet = new global::Gtk.Image();
			this.imageIDNet.Name = "imageIDNet";
			this.vbox3.Add(this.imageIDNet);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.imageIDNet]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.vbox1.Add(this.vbox3);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox3]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Homogeneous = true;
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.labelUsuario = new global::Gtk.Label();
			this.labelUsuario.Name = "labelUsuario";
			this.labelUsuario.LabelProp = global::Mono.Unix.Catalog.GetString("Usuario:");
			this.labelUsuario.Justify = ((global::Gtk.Justification)(2));
			this.hbox1.Add(this.labelUsuario);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.labelUsuario]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.entryUser = new global::Gtk.Entry();
			this.entryUser.CanFocus = true;
			this.entryUser.Name = "entryUser";
			this.entryUser.IsEditable = true;
			this.entryUser.InvisibleChar = '•';
			this.hbox1.Add(this.entryUser);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.entryUser]));
			w5.Position = 1;
			w5.Fill = false;
			this.vbox1.Add(this.hbox1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Homogeneous = true;
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.labelContrasenia = new global::Gtk.Label();
			this.labelContrasenia.Name = "labelContrasenia";
			this.labelContrasenia.LabelProp = global::Mono.Unix.Catalog.GetString("Contraseña:");
			this.labelContrasenia.Justify = ((global::Gtk.Justification)(2));
			this.hbox2.Add(this.labelContrasenia);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.labelContrasenia]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.entryPassword = new global::Gtk.Entry();
			this.entryPassword.CanFocus = true;
			this.entryPassword.Name = "entryPassword";
			this.entryPassword.IsEditable = true;
			this.entryPassword.InvisibleChar = '•';
			this.hbox2.Add(this.entryPassword);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.entryPassword]));
			w8.Position = 1;
			w8.Fill = false;
			this.vbox1.Add(this.hbox2);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.buttonRegister = new global::Gtk.Button();
			this.buttonRegister.CanFocus = true;
			this.buttonRegister.Name = "buttonRegister";
			this.buttonRegister.UseUnderline = true;
			this.buttonRegister.Label = global::Mono.Unix.Catalog.GetString("Registrarse");
			this.hbox3.Add(this.buttonRegister);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.buttonRegister]));
			w10.Position = 0;
			w10.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.labelState = new global::Gtk.Label();
			this.labelState.Name = "labelState";
			this.labelState.LabelProp = "";
			this.labelState.Justify = ((global::Gtk.Justification)(2));
			this.hbox3.Add(this.labelState);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.labelState]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.buttonOk = new global::Gtk.Button();
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = global::Mono.Unix.Catalog.GetString("Iniciar sesión");
			this.hbox3.Add(this.buttonOk);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.buttonOk]));
			w12.Position = 2;
			w12.Fill = false;
			this.vbox1.Add(this.hbox3);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox3]));
			w13.Position = 3;
			w13.Expand = false;
			w13.Fill = false;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 330;
			this.DefaultHeight = 171;
			this.Show();
			this.buttonRegister.Clicked += new global::System.EventHandler(this.OnButtonRegisterClicked);
			this.buttonOk.Clicked += new global::System.EventHandler(this.OnButtonOkClicked);
		}
	}
}
