
// This file has been generated by the GUI designer. Do not modify.
namespace IDNetSoftware
{
	public partial class AcercadeDialog
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.Label labelTitulo;

		private global::Gtk.Label labelDescripcion;

		private global::Gtk.Label labelAutores;

		private global::Gtk.Button buttonOk;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget IDNetSoftware.AcercadeDialog
			this.Name = "IDNetSoftware.AcercadeDialog";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.DefaultWidth = 200;
			this.DefaultHeight = 200;
			// Internal child IDNetSoftware.AcercadeDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.labelTitulo = new global::Gtk.Label();
			this.labelTitulo.Name = "labelTitulo";
			this.labelTitulo.LabelProp = global::Mono.Unix.Catalog.GetString("IDNet");
			this.labelTitulo.Justify = ((global::Gtk.Justification)(2));
			this.vbox2.Add(this.labelTitulo);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.labelTitulo]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.labelDescripcion = new global::Gtk.Label();
			this.labelDescripcion.Name = "labelDescripcion";
			this.labelDescripcion.LabelProp = global::Mono.Unix.Catalog.GetString("IDNet es un framework de conexión P2P de bases de datos distribuidas e independie" +
					"ntes");
			this.labelDescripcion.Justify = ((global::Gtk.Justification)(2));
			this.vbox2.Add(this.labelDescripcion);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.labelDescripcion]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.labelAutores = new global::Gtk.Label();
			this.labelAutores.Name = "labelAutores";
			this.labelAutores.LabelProp = global::Mono.Unix.Catalog.GetString("Autores: Lorenzo José de la Paz Suárez y Juan Mas Aguilar");
			this.vbox2.Add(this.labelAutores);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.labelAutores]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			w1.Add(this.vbox2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(w1[this.vbox2]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Internal child IDNetSoftware.AcercadeDialog.ActionArea
			global::Gtk.HButtonBox w6 = this.ActionArea;
			w6.Name = "dialog1_ActionArea";
			w6.Spacing = 10;
			w6.BorderWidth = ((uint)(5));
			w6.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(2));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget(this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w7 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w6[this.buttonOk]));
			w7.Expand = false;
			w7.Fill = false;
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Show();
			this.buttonOk.Clicked += new global::System.EventHandler(this.OnButtonOkClicked);
		}
	}
}
