
// This file has been generated by the GUI designer. Do not modify.
namespace IDNetSoftware
{
	public partial class ConnectionWindow
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.Button buttonConexion;

		private global::Gtk.Button buttonEsquema;

		private global::Gtk.Button buttonSelect;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Fixed fixed1;

		private global::Gtk.Fixed fixed2;

		private global::Gtk.Button buttonCancel;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget IDNetSoftware.ConnectionWindow
			this.Name = "IDNetSoftware.ConnectionWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("ConnectionWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Container child IDNetSoftware.ConnectionWindow.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.buttonConexion = new global::Gtk.Button();
			this.buttonConexion.CanFocus = true;
			this.buttonConexion.Name = "buttonConexion";
			this.buttonConexion.UseUnderline = true;
			this.buttonConexion.Label = global::Mono.Unix.Catalog.GetString("Establecer conexión");
			this.vbox2.Add(this.buttonConexion);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.buttonConexion]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.buttonEsquema = new global::Gtk.Button();
			this.buttonEsquema.CanFocus = true;
			this.buttonEsquema.Name = "buttonEsquema";
			this.buttonEsquema.UseUnderline = true;
			this.buttonEsquema.Label = global::Mono.Unix.Catalog.GetString("Solicitar Esquema de la BBDD");
			this.vbox2.Add(this.buttonEsquema);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.buttonEsquema]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.buttonSelect = new global::Gtk.Button();
			this.buttonSelect.CanFocus = true;
			this.buttonSelect.Name = "buttonSelect";
			this.buttonSelect.UseUnderline = true;
			this.buttonSelect.Label = global::Mono.Unix.Catalog.GetString("Realizar consulta");
			this.vbox2.Add(this.buttonSelect);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.buttonSelect]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			this.hbox1.Add(this.fixed1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.fixed1]));
			w4.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.fixed2 = new global::Gtk.Fixed();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			this.hbox1.Add(this.fixed2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.fixed2]));
			w5.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonCancel = new global::Gtk.Button();
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = global::Mono.Unix.Catalog.GetString("Cancel");
			this.hbox1.Add(this.buttonCancel);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.buttonCancel]));
			w6.Position = 2;
			this.vbox2.Add(this.hbox1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox1]));
			w7.Position = 3;
			w7.Expand = false;
			w7.Fill = false;
			this.Add(this.vbox2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 402;
			this.DefaultHeight = 158;
			this.Show();
			this.buttonConexion.Clicked += new global::System.EventHandler(this.OnButtonConexionClicked);
			this.buttonEsquema.Clicked += new global::System.EventHandler(this.OnButtonEsquemaClicked);
			this.buttonSelect.Clicked += new global::System.EventHandler(this.OnButtonSelectClicked);
			this.buttonCancel.Clicked += new global::System.EventHandler(this.OnButtonCancelClicked);
		}
	}
}
