
// This file has been generated by the GUI designer. Do not modify.
namespace IDNetSoftware
{
	public partial class LaunchIDNetDaemonWindow
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.Label labelInfoArranque;

		private global::Gtk.Label labelText1;

		private global::Gtk.Entry entryFirst;

		private global::Gtk.HSeparator hseparator2;

		private global::Gtk.Label label3;

		private global::Gtk.Entry entrySecond;

		private global::Gtk.HSeparator hseparator1;

		private global::Gtk.Label labelExplicacion;

		private global::Gtk.HSeparator hseparator3;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Button buttonSalir;

		private global::Gtk.Button buttonOK;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget IDNetSoftware.LaunchIDNetDaemonWindow
			this.Name = "IDNetSoftware.LaunchIDNetDaemonWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("LaunchIDNetDaemonWindow");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource("iconoIDNetSoftware");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Container child IDNetSoftware.LaunchIDNetDaemonWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.labelInfoArranque = new global::Gtk.Label();
			this.labelInfoArranque.Name = "labelInfoArranque";
			this.labelInfoArranque.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Necesita arrancar IDNetDaemon.\n Siga las siguientes intrucciones:</b>");
			this.labelInfoArranque.UseMarkup = true;
			this.labelInfoArranque.Justify = ((global::Gtk.Justification)(2));
			this.vbox1.Add(this.labelInfoArranque);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.labelInfoArranque]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.labelText1 = new global::Gtk.Label();
			this.labelText1.Name = "labelText1";
			this.labelText1.LabelProp = global::Mono.Unix.Catalog.GetString("Abre la línea de comandos y ejecute el siguiente comando:");
			this.vbox1.Add(this.labelText1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.labelText1]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.entryFirst = new global::Gtk.Entry();
			this.entryFirst.CanFocus = true;
			this.entryFirst.Name = "entryFirst";
			this.entryFirst.IsEditable = false;
			this.entryFirst.InvisibleChar = '•';
			this.vbox1.Add(this.entryFirst);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.entryFirst]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hseparator2 = new global::Gtk.HSeparator();
			this.hseparator2.Name = "hseparator2";
			this.vbox1.Add(this.hseparator2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hseparator2]));
			w4.Position = 3;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("A continuación, lance el demonio mediante el siguiente comando:");
			this.vbox1.Add(this.label3);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.label3]));
			w5.Position = 4;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.entrySecond = new global::Gtk.Entry();
			this.entrySecond.CanFocus = true;
			this.entrySecond.Name = "entrySecond";
			this.entrySecond.IsEditable = false;
			this.entrySecond.InvisibleChar = '•';
			this.vbox1.Add(this.entrySecond);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.entrySecond]));
			w6.Position = 5;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator();
			this.hseparator1.Name = "hseparator1";
			this.vbox1.Add(this.hseparator1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hseparator1]));
			w7.Position = 6;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.labelExplicacion = new global::Gtk.Label();
			this.labelExplicacion.Name = "labelExplicacion";
			this.labelExplicacion.LabelProp = global::Mono.Unix.Catalog.GetString("Mediante los comandos ejecutados, estamos lanzando el demonio de IDNet, \nel cuál " +
					"permite a los usuarios de la Organización Virtual la conexión a nosotros\ny con e" +
					"llo,  a nuestras bases de datos.");
			this.vbox1.Add(this.labelExplicacion);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.labelExplicacion]));
			w8.Position = 7;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hseparator3 = new global::Gtk.HSeparator();
			this.hseparator3.Name = "hseparator3";
			this.vbox1.Add(this.hseparator3);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hseparator3]));
			w9.Position = 8;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Homogeneous = true;
			this.hbox1.Spacing = 6;
			this.hbox1.BorderWidth = ((uint)(3));
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonSalir = new global::Gtk.Button();
			this.buttonSalir.CanFocus = true;
			this.buttonSalir.Name = "buttonSalir";
			this.buttonSalir.UseUnderline = true;
			this.buttonSalir.Label = global::Mono.Unix.Catalog.GetString("Salir");
			this.hbox1.Add(this.buttonSalir);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.buttonSalir]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonOK = new global::Gtk.Button();
			this.buttonOK.CanFocus = true;
			this.buttonOK.Name = "buttonOK";
			this.buttonOK.UseUnderline = true;
			this.buttonOK.Label = global::Mono.Unix.Catalog.GetString("OK");
			this.hbox1.Add(this.buttonOK);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.buttonOK]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			this.vbox1.Add(this.hbox1);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
			w12.Position = 9;
			w12.Expand = false;
			w12.Fill = false;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 747;
			this.DefaultHeight = 268;
			this.Show();
			this.buttonSalir.Clicked += new global::System.EventHandler(this.OnButtonSalirClicked);
			this.buttonOK.Clicked += new global::System.EventHandler(this.OnButtonOKClicked);
		}
	}
}
